### ISSUE TITLE
Fatal error when using Performance->quickMenu

### ISSUE THREAD

**Issue by cpsitgmbh** [dwenzel/t3events#38]
When using switchableControllerActions: „Performance->quickMenu“ a fatal error is shown in the frontend:
`Fatal error: Cannot use TYPO3\CMS\Extbase\Domain\Model\Category as Category because the name is already in use in [...]/typo3conf/ext/t3events/Classes/Domain/Model/CategorizableTrait.php on line 4`

Previously I've updatet the extension from version 0.16.2 to 0.19.1 (master).

**Comment by cpsitgmbh** [comment]
I can force the error message when clearing the system cache and then reload the page where (in my case) event list and quickmenu are placed on.

my settings are:
- TYPO3 CMS 6.2.19
- PHP version 5.6.18

**Comment by dwenzel** [comment]
Thank you @erauchstein!
We close this issue allthough the ultimate cause is still a miracle ;)
