### ISSUE TITLE
Pagination don't keep filter settings of quickmenu

### ISSUE THREAD

**Issue by cpsitgmbh** [dwenzel/t3events#39]
When using quickmenu to filter the list view, the links in pagination don't keep the filter settings.
I can reproduce this with version 0.19.0, 0.20.0 and 0.21.0.

As workaround I outsourced the template files and added configuration to use query string, but than I get a frontend error:
`Uncaught TYPO3 Exception
#1320830018: The given string was not appended with a valid HMAC.`
(for this issue see #43 ).

Templates\ViewHelpers\Widget\Paginate:
- added `addQueryStringMethod="{configuration.addQueryStringMethod}` to all "f:widget.link"
- added argument "configuration:configuration" to sections "paginator"

Templates\Performance\List.html (respectively Templates\Event\List.html):
- added `addQueryStringMethod: 'POST'` to "f:widget.paginate"

**Comment by dwenzel** [comment]
@frau-liessmann: should be fixed - close it?

**Comment by frau-liessmann** [comment]
Yes, the issue can be closed.
