### ISSUE TITLE
RTE-Links in events description

### ISSUE THREAD

**Issue by Vendragor** [dwenzel/t3events#44]
Internal links do not open properly when created in rte field "description" of model "event".

Possible fix, working for me:

tx_t3events_domain_model_event.php:
`'defaultExtras' => 'richtext:rte_transform[flag=rte_enabled|mode=ts]'` (line 192)

**Comment by dwenzel** [comment]
Hi @Vendragor 
Great! Could you please verifiy that your fix works for TYPO3 version 6.2 and 7.6 and commit it in the develop branch.

**Comment by erauchstein** [comment]
Bug fix for TYPO3 version 6.2 and 7.6 tested and commitet in dev branche.

The bug fix itself comes from the following forge ticket:

https://forge.typo3.org/issues/60467
