### ISSUE TITLE
CalendarItemStorage not found

### ISSUE THREAD

**Issue by mmasmoudi** [dwenzel/t3events#52]
Hello,

I have installed t3events on my project, when using the list view, all goes fine but for calendar view, the frontend crash and this is the error message:
Fatal error: Class 'DWenzel\T3calendar\Persistence\CalendarItemStorage' not found in typo3cms/theater-morgenstern/typo3conf/ext/t3events/Classes/Controller/EventController.php on line 163

Typo3 7.6.15
t3events:0.31.0
t3calendar: 0.1.1

Typoscript Template already included.
I Try Clear all cache from installtool.
I Try to reinstall the extensions t3events and t3calendar multiple times, but no success.

**Comment by dwenzel** [comment]
Hi @mmasmoudi,
Thank you for reporting this issue. 
Obviously I made a mistake on the last release of t3events. 
The CalendarItemStorage class was implemented *after* version 0.1.1 of _t3calendar_.
Please stay in tune - I will release new versions of both extensions within a few days.

The current development branch of _t3calendar_ should work.
