### ISSUE TITLE
Issue when create an new event item

### ISSUE THREAD

**Issue by mmasmoudi** [dwenzel/t3events#61]
Hi,

I have this error when i try to create a new item "event":

2: SQL error: 'Unknown column 'categories' in 'field list'' (tx_t3events_domain_model_event:NEW5916edbb8f344342168971)

I have tried the last version of this extension 0.33
Typo3:7.6.18

**Comment by dwenzel** [comment]
Hi, just use the `Database compare` in Install Tool to add the missing column.
