### ISSUE TITLE
Different format for start and end date

### ISSUE THREAD

**Issue by SetteT3** [dwenzel/t3events#72]
DateRangeViewHelper should allow to display a start date in a format different from "format" and "endFormat".

**Comment by dwenzel** [comment]
@SetteT3 Thank you for your suggestion. Please use the following ViewHelpers:
`DWenzel\T3events\ViewHelpers\Format\Performance\DateRangeViewHelper` and 
`DWenzel\T3events\ViewHelpers\Format\Event\DateRangeViewHelper`

see: https://github.com/dwenzel/t3events/blob/master/Documentation/ViewHelpers/ViewHelpers.md
