### ISSUE TITLE
Exception handling in show action

### ISSUE THREAD

**Issue by kaywalker** [dwenzel/t3events#73]
The typoscript setup for error handling of the EventController showAction is undefined. 
Should be:
`plugin.tx_t3events.settings.event.show.errorHandling = {$plugin.tx_t3events.settings.detail.errorHandling}`

**Comment by dwenzel** [comment]
@kaywalker Thank you for reporting. For historical reasons the TypoScript settings of the 'show' action are defined in `plugin.tx_t3events.event.detail`. I will add them at the expected place though.
