### ISSUE TITLE
No events shown in calendar

### ISSUE THREAD

**Issue by blueamerican** [dwenzel/t3events#75]
I use
TYPO3 V8
t3events | 0.37.3
t3calendar | 0.4.0

Althought i created events and performances, none of them is shown in the calendar.
What could be the reason?
![t3events](https://user-images.githubusercontent.com/5647051/44854201-3aed3300-ac68-11e8-91b5-f88171416496.jpg)

**Comment by dwenzel** [comment]
Hi @blueamerican 
your screenshots helps a lot. The item entries are what is shown of your events per default.
The default template of t3calendar doesn't "know" anything about the fields/structure of a calendarItem. Therefore I decided to implement only a very basic partial. 

Please register an additionnal partial path add a custom partial for `

**Comment by dwenzel** [comment]
I consider the question answered.
