### ISSUE TITLE
Saving new event record in TYPO3 9 fails

### ISSUE THREAD

**Issue by mspfr** [dwenzel/t3events#80]
if group field no default value it does not save.

**Comment by dwenzel** [comment]
**steps**
* no Organizer record exists (table `tx_t3events_domain_model_organizer` empty) 
* open list view in TYPO3 Backend 
* create new record (`tx_t3events_domain_model_event`)
* fill in required field `headline`
* save record

**expected**
* record is saved to DB

**observed**
* record is not saved
* error message: 

> 2: SQL error: 'Incorrect integer value: '' for column `db`.`tx_t3events_domain_model_event`.`organizer` at row 1' (tx_t3events_domain_model_event:NEW5d0c90fb238c3195710185)

**Comment by dwenzel** [comment]
@mspfr I could reproduce this issues for a installation with 
* Maria DB 10.2.22 
*  sql_mode: `STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION` (default)

Adding `default = 0`  in configuration for field `tx_t3events_domain_model_event.organizer` fixed it.
```php
'organizer' => [
            'exclude' => 1,
            'label' => $ll . ':tx_t3events_domain_model_event.organizer',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_t3events_domain_model_organizer',
                'l10nmode' => 'mergeIfNotBlank',
                'size' => 1,
                'default' => 0,
                'minitems' => 0,
                'maxitems' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true
                ]
            ],
        ],
```
