### ISSUE TITLE
Problem with performances array of an event

### ISSUE THREAD

**Issue by rteinze** [dwenzel/t3events#83]
Problems while showing the eventlocation details of all performances of one event. An access to deep laying values. To call values of one eventlocation you MUST call the `performance.eventlocation` at all, to have access to deeper values inside the eventLocation array. Strange! Here is the code that works:

**template section: Event/Show.html**
```
<f:section name="main">
    <f:render partial="TemplateVariants/Event/Show/Template20" arguments="{_all}" />
</f:section>
```

**partial: TemplateVariants/Event/Show/Template20.html**
```
<h2>Veranstalter</h2>
<!-- {event.performances.0.eventLocation} !!! DOES NOT WORK WITHOUT THIS !!! -->
<p>{event.performances.0.eventLocation.name}
    <br>{event.performances.0.eventLocation.address}
    <br>{event.performances.0.eventLocation.zip} {event.performances.0.eventLocation.place}
</p>
```

Typo3 9.5.11
t3events 1.1.0

**Comment by dwenzel** [comment]
Hi @rteinze and thank you for reporting this issue. 
I did not observe this behaviour and it seems quite strange.

With which TYPO3 version does it happen?

**Comment by rteinze** [comment]
Hi @dwenzel thank you for your reply. 
I reduced the original posting to the minimal code to reproduce the bug. The loop and child-partial are not necessary.

Versions:
Typo3 9.5.11
t3events 1.1.0
> 
> 
> Hi @rteinze and thank you for reporting this issue.
> I did not observe this behaviour and it seems quite strange.
> 
> With which TYPO3 version does it happen?

**Comment by dwenzel** [comment]
@rteinze I did not dig deeper into this issue but I am quite sure, this is not an issue with `t3events`. 

For clarification: Even though the so called `array access notation` is used, the value of `{performances}` or `{events}` is not an array but an instance of `TYPO3\CMS\Extbase\Persistence\QueryResultInterface` (see [TYPO3 API](https://api.typo3.org/9.5/interface_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_persistence_1_1_query_result_interface.html)). 

This is a "lazy proxy" and does *not* fetch any result from the database before an object is accessed. So your observation when trying to access a property might indicate that the object of type `EventLocation` has not been reconstituted yet.
