### ISSUE TITLE
[BUG] Events are not shown if no performance is set

### ISSUE THREAD

**Issue by rteinze** [dwenzel/t3events#86]
**To Reproduce**
1. create event (w/o any performances)
2. create content-element (t3events-plugin) to output a list of all events on a page
3. open the page where the list should be shown
3. event is visible
4. assign a performance to this event
5. event is still visible
6. hide or delete every performance of this event
7. event is not visible anymore 

**Expected behavior**
Event should be visible.

**Setup:**
 - TYPO3 version: [e.g. 9.5.14]
 - t3events version [e.g. 1.1.0]
 - PHP [e.g. 7.3]
 - Database: [MySql 5.7.30-1]

Is there any workaround?

Thank you very much.

**Comment by rteinze** [comment]
UPDATE:
If there are never performances created - it works. Events are shown as expected.

If one create a performance and hide/delete it afterwards - then the Event is not shown anymore.

I add this to the original post.

**Comment by dwenzel** [comment]
@rteinze Thank you for reporting this issue.
I did not observe this behaviour before. Are sure that your plugin displays an event list (and not a performance list)? 

In this case the behavoiur would be intended. 

An event list should list events without performances if it is not constraint by start and/or end date.

**Comment by rteinze** [comment]
@dwenzel I'm pretty shure - the plugin is displaying an event list. No constraints are set.

And - I continued to research - it's not the list, but the evet that's not shown if there are no performances. 

Again: On creation the event is shown in the event list. But if I create and remove one performance, then this event is not shown anymore.

**Comment by dwenzel** [comment]
I'm sorry, I cant reproduce this issue. 

I created a minimal setup following your description 
* t3events in `develop` at aa064ffe6e9cf
* TYPO3 9.5.18
* PHP  7.2.25
* MariaDB 10.2.27
* Template record with minimal TypoScript for PAGE object
* include TypoScript from extension
* create an event record
* setup plugin on root page with action `Event List/Detail [Event->list;Event->show]` selected

=> Frontend shows list with event.

* add single performance with start date in future

=> Frontend still lists event.

* hide performance
* clear cache

=> Frontend still shows list with event.

* delete performance
* clear cache

Frontend still shows list with event.

You may checkout my setup here: https://github.com/dwenzel/t3events-bundle/tree/develop
It requires Docker and [DDEV](https://ddev.readthedocs.io/en/stable/) and contains a database dump (.ddev/t3events-t9.sql.gz)
