### ISSUE TITLE
Any plans to upgrade for TYPO3 CMS 10?

### ISSUE THREAD

**Issue by rteinze** [dwenzel/t3events#87]
Hello, do you have any plans to upgrade your nice extension? There is no other extension like yours with events separated from performances. We need you guys.

Thanks a lot.
René

**Comment by dwenzel** [comment]
Hello René and thanks for your kind request.

We will most probably upgrade the extension for TYPO3 10 in January or February 2021 (mayby earlier). 

Unfortunatly I'm not able to spend much of my spare time for it currently, but my employeer commited himself to support it. 
I don't expect much trouble during the upgrade and would happily accept pull request..

cheers
Dirk
